[merge-tools.vimdiff]
diff-invocation-mode = "file-by-file"

[ui]
default-command = "status"
diff-editor     = "meld"
merge-editor    = "meld"

[colors]
"diff token" = { underline = false }

[user]
email = "shaver@off.net"
name  = "Mike Shaver"

[[--scope]]
--when.repositories = ["~/ts/"]
--when.hostname     = ["alchemist"]
[--scope.user]
email = "shaver@tailscale.com"

[revsets]
bookmark-advance-to = "@-"

[templates]
# from https://andre.arko.net/2025/09/28/stupid-jj-tricks/
draft_commit_description = '''
  concat(
    coalesce(description, default_commit_description, "\n"), 
    surround(
      "\nJJ: This commit contains the following changes:\n", "", 
      indent("JJ:     ", diff.stat(72)), 
    ),
    "\nJJ: ignore-rest\n", 
    diff.git(), 
)
'''
